"""
Complete fix for Lambda deserialization error.
Changes:
  - Cell 9:  checkpoint paths -> .weights.h5
  - Cell 9:  add cleanup of old .keras files from Drive
  - Cell 18: ModelCheckpoint save_weights_only=True
  - Cell 20: ModelCheckpoint save_weights_only=True
  - Cell 23: always use in-memory model (no load_model ever)
"""
import json

with open('notebooks/colab_train.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)
cells = nb['cells']

# ── Cell 9: update checkpoint paths + cleanup old .keras files ────────────────
cells[9]['source'] = [
    "import os, json, time, shutil\n",
    "from pathlib import Path\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import tensorflow as tf\n",
    "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n",
    "\n",
    "# Dataset location (flat — one subfolder per class, no train/val/test)\n",
    "DATA_DIR   = '/content/drive/MyDrive/udms-project/data/processed/all'\n",
    "MODELS_DIR = '/content/drive/MyDrive/udms-project/models'\n",
    "\n",
    "# Weights-only checkpoints — avoids Lambda/focal_loss serialization entirely\n",
    "PHASE1_CKPT   = f'{MODELS_DIR}/phase1_best.weights.h5'\n",
    "PHASE2_CKPT   = f'{MODELS_DIR}/phase2_best.weights.h5'\n",
    "TFLITE_OUT    = f'{MODELS_DIR}/classifier.tflite'\n",
    "LABEL_MAP_OUT = f'{MODELS_DIR}/label_map.json'\n",
    "\n",
    "IMG_SIZE        = (224, 224)\n",
    "INPUT_SHAPE     = (224, 224, 3)\n",
    "BATCH_SIZE      = 32\n",
    "NUM_CLASSES     = 5\n",
    "TEMP_SPLIT      = 0.30\n",
    "SEED            = 42\n",
    "PHASE1_LR       = 1e-3\n",
    "PHASE1_EPOCHS   = 20\n",
    "PHASE2_LR       = 1e-5\n",
    "PHASE2_EPOCHS   = 15\n",
    "UNFREEZE_LAYERS = 30\n",
    "EARLY_STOP_PAT  = 5\n",
    "\n",
    "UDMS_CATEGORIES = [\n",
    "    'bad_drainage', 'damaged_signage', 'illegal_dumping',\n",
    "    'potholes', 'vegetation_overgrowth',\n",
    "]\n",
    "CATEGORY_LABELS = {\n",
    "    'bad_drainage':          'Bad Drainage / Water Sewage Issues',\n",
    "    'damaged_signage':       'Damaged Signage / Infrastructure',\n",
    "    'illegal_dumping':       'Illegal Dumping / Garbage',\n",
    "    'potholes':              'Pothole / Road Damage',\n",
    "    'vegetation_overgrowth': 'Vegetation Overgrowth',\n",
    "}\n",
    "\n",
    "os.makedirs(MODELS_DIR, exist_ok=True)\n",
    "\n",
    "# Delete stale .keras checkpoints from Drive — they contain the old Lambda\n",
    "# layer and can never be loaded.  The new .weights.h5 files are weights-only.\n",
    "for stale in ['phase1_best.keras', 'phase2_best.keras']:\n",
    "    stale_path = os.path.join(MODELS_DIR, stale)\n",
    "    if os.path.exists(stale_path):\n",
    "        os.remove(stale_path)\n",
    "        print(f'Removed stale checkpoint: {stale}')\n",
    "\n",
    "if not os.path.isdir(DATA_DIR):\n",
    "    raise FileNotFoundError(\n",
    "        f'Dataset not found: {DATA_DIR}\\n'\n",
    "        'Upload data/processed/all/ to MyDrive/udms-project/data/processed/'\n",
    "    )\n",
    "\n",
    "classes_found = sorted([\n",
    "    d for d in os.listdir(DATA_DIR)\n",
    "    if os.path.isdir(os.path.join(DATA_DIR, d))\n",
    "])\n",
    "print(f'Data dir    : {DATA_DIR}')\n",
    "print(f'Models dir  : {MODELS_DIR}')\n",
    "print(f'Classes ({len(classes_found)}): {classes_found}')\n",
    "for cls in classes_found:\n",
    "    count = len(os.listdir(os.path.join(DATA_DIR, cls)))\n",
    "    print(f'  {cls:<25} {count:>5,} images')\n",
    "print('Configuration loaded.')\n",
]

# ── Cell 18: Phase 1 training — save_weights_only=True ───────────────────────
cells[18]['source'] = [
    "\n",
    "def plot_history(history, title_prefix: str):\n",
    "    epochs = range(1, len(history.history['accuracy']) + 1)\n",
    "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 4))\n",
    "    ax1.plot(epochs, history.history['accuracy'],     'b-o', ms=4, label='train')\n",
    "    ax1.plot(epochs, history.history['val_accuracy'], 'r-o', ms=4, label='val')\n",
    "    ax1.set_title(f'{title_prefix} — Accuracy')\n",
    "    ax1.set_xlabel('Epoch'); ax1.set_ylabel('Accuracy')\n",
    "    ax1.legend(); ax1.grid(True, alpha=0.3)\n",
    "    ax2.plot(epochs, history.history['loss'],     'b-o', ms=4, label='train')\n",
    "    ax2.plot(epochs, history.history['val_loss'], 'r-o', ms=4, label='val')\n",
    "    ax2.set_title(f'{title_prefix} — Loss')\n",
    "    ax2.set_xlabel('Epoch'); ax2.set_ylabel('Loss')\n",
    "    ax2.legend(); ax2.grid(True, alpha=0.3)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "model.compile(\n",
    "    optimizer=tf.keras.optimizers.Adam(learning_rate=PHASE1_LR),\n",
    "    loss=focal_loss(gamma=2.0),\n",
    "    metrics=['accuracy'],\n",
    ")\n",
    "\n",
    "phase1_callbacks = [\n",
    "    tf.keras.callbacks.ModelCheckpoint(\n",
    "        filepath=PHASE1_CKPT,\n",
    "        monitor='val_accuracy',\n",
    "        save_best_only=True,\n",
    "        save_weights_only=True,   # weights only — no architecture serialization\n",
    "        mode='max',\n",
    "        verbose=1,\n",
    "    ),\n",
    "    tf.keras.callbacks.EarlyStopping(\n",
    "        monitor='val_loss',\n",
    "        patience=EARLY_STOP_PAT,\n",
    "        restore_best_weights=True,\n",
    "        verbose=1,\n",
    "    ),\n",
    "    tf.keras.callbacks.CSVLogger(f'{MODELS_DIR}/phase1_log.csv'),\n",
    "]\n",
    "\n",
    "print('=' * 60)\n",
    "print('PHASE 1 — Training classification head (backbone frozen)')\n",
    "print('=' * 60)\n",
    "\n",
    "history1 = model.fit(\n",
    "    train_ds,\n",
    "    validation_data=val_ds,\n",
    "    epochs=PHASE1_EPOCHS,\n",
    "    callbacks=phase1_callbacks,\n",
    "    class_weight=class_weights,\n",
    ")\n",
    "\n",
    "print(f'\\nPhase 1 complete — best val_accuracy: {max(history1.history[\"val_accuracy\"]):.4f}')\n",
    "plot_history(history1, 'Phase 1')\n",
]

# ── Cell 20: Phase 2 training — save_weights_only=True ───────────────────────
cells[20]['source'] = [
    "\n",
    "backbone = next(\n",
    "    l for l in model.layers\n",
    "    if 'mobilenet' in l.name.lower() and hasattr(l, 'layers')\n",
    ")\n",
    "backbone.trainable = True\n",
    "for layer in backbone.layers[:-UNFREEZE_LAYERS]:\n",
    "    layer.trainable = False\n",
    "\n",
    "trainable_now = sum(tf.size(w).numpy() for w in model.trainable_weights)\n",
    "print(f'Trainable params after unfreeze : {trainable_now:,}')\n",
    "print(f'Unfrozen backbone layers        : {UNFREEZE_LAYERS}')\n",
    "\n",
    "model.compile(\n",
    "    optimizer=tf.keras.optimizers.Adam(learning_rate=PHASE2_LR),\n",
    "    loss=focal_loss(gamma=2.0),\n",
    "    metrics=['accuracy'],\n",
    ")\n",
    "\n",
    "phase2_callbacks = [\n",
    "    tf.keras.callbacks.ModelCheckpoint(\n",
    "        filepath=PHASE2_CKPT,\n",
    "        monitor='val_accuracy',\n",
    "        save_best_only=True,\n",
    "        save_weights_only=True,   # weights only — no architecture serialization\n",
    "        mode='max',\n",
    "        verbose=1,\n",
    "    ),\n",
    "    tf.keras.callbacks.EarlyStopping(\n",
    "        monitor='val_loss',\n",
    "        patience=EARLY_STOP_PAT,\n",
    "        restore_best_weights=True,\n",
    "        verbose=1,\n",
    "    ),\n",
    "    tf.keras.callbacks.ReduceLROnPlateau(\n",
    "        monitor='val_loss',\n",
    "        factor=0.5,\n",
    "        patience=3,\n",
    "        min_lr=1e-7,\n",
    "        verbose=1,\n",
    "    ),\n",
    "    tf.keras.callbacks.CSVLogger(f'{MODELS_DIR}/phase2_log.csv'),\n",
    "]\n",
    "\n",
    "print('\\n' + '='*60)\n",
    "print('PHASE 2 — Fine-tuning top-30 backbone layers')\n",
    "print('='*60)\n",
    "\n",
    "history2 = model.fit(\n",
    "    train_ds,\n",
    "    validation_data=val_ds,\n",
    "    epochs=PHASE2_EPOCHS,\n",
    "    callbacks=phase2_callbacks,\n",
    "    class_weight=class_weights,\n",
    ")\n",
    "\n",
    "best_p2 = max(history2.history['val_accuracy'])\n",
    "print(f'\\nPhase 2 complete — best val_accuracy: {best_p2:.4f}')\n",
]

# ── Cell 23: evaluation — use in-memory model (EarlyStopping already restored) ─
cells[23]['source'] = [
    "# EarlyStopping(restore_best_weights=True) restores best weights into `model`.\n",
    "# We never call load_model() — avoids all serialization issues.\n",
    "best_model = model\n",
    "print('Using in-memory model — best weights already restored by EarlyStopping.')\n",
    "\n",
    "y_true_list, y_prob_list = [], []\n",
    "for images, labels in test_ds:\n",
    "    probs = best_model.predict(images, verbose=0)\n",
    "    y_prob_list.append(probs)\n",
    "    y_true_list.append(np.argmax(labels.numpy(), axis=1))\n",
    "\n",
    "y_true = np.concatenate(y_true_list)\n",
    "y_prob = np.concatenate(y_prob_list)\n",
    "y_pred = np.argmax(y_prob, axis=1)\n",
    "\n",
    "test_acc = accuracy_score(y_true, y_pred)\n",
    "print(f'Test accuracy : {test_acc:.4f}  ({test_acc * 100:.2f}%)')\n",
    "print(f'Test samples  : {len(y_true):,}')\n",
    "print()\n",
    "print('Classification Report:')\n",
    "print(classification_report(y_true, y_pred, target_names=CLASS_NAMES, digits=3))\n",
]

with open('notebooks/colab_train.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('Done. Cells 9, 18, 20, 23 fixed — save_weights_only=True, stale .keras removed.')
